export const columns = [
  {
    id: 1,
    title: "ID",
    render: (row) => row.id,
    accessor: "id",
    sortable: true,
  },
  {
    id: 2,
    title: "First Name",
    render: (row) => row.firstName,
    accessor: "firstName",
    sortable: true,
  },
  {
    id: 3,
    title: "Last Name",
    render: (row) => row.lastName,
    accessor: "lastName",
    sortable: true,
  },
  {
    id: 4,
    title: "Email",
    render: (row) => row.email,
    accessor: "email",
    sortable: true,
  },
  {
    id: 5,
    title: "Phone",
    render: (row) => row.phone,
    accessor: "phone",
    sortable: true,
  },
  {
    id: 6,
    title: "Address",
    render: (row) => row.address,
    accessor: "address",
    sortable: true,
  },
  {
    id: 7,
    title: "City",
    render: (row) => row.city,
    accessor: "city",
    sortable: true,
  },
  {
    id: 8,
    title: "State",
    render: (row) => row.state,
    accessor: "state",
    sortable: true,
  },
  {
    id: 9,
    title: "Country",
    render: (row) => row.country,
    accessor: "country",
    sortable: true,
  },
  {
    id: 10,
    title: "Zip Code",
    render: (row) => row.zipCode,
    accessor: "zipCode",
    sortable: true,
  },
];
