export const dataList = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phone: "123-456-7890",
    address: "123 Elm Street",
    city: "Somewhere",
    state: "CA",
    country: "USA",
    zipCode: "12345",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phone: "234-567-8901",
    address: "456 Oak Street",
    city: "Anywhere",
    state: "TX",
    country: "USA",
    zipCode: "67890",
  },
  // Add more data objects to reach 25 entries
  {
    id: "3",
    firstName: "Emily",
    lastName: "Johnson",
    email: "emily.johnson@example.com",
    phone: "345-678-9012",
    address: "789 Pine Street",
    city: "Everywhere",
    state: "NY",
    country: "USA",
    zipCode: "11223",
  },
  {
    id: "4",
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@example.com",
    phone: "456-789-0123",
    address: "101 Maple Street",
    city: "Nowhere",
    state: "FL",
    country: "USA",
    zipCode: "44556",
  },
  {
    id: "5",
    firstName: "Jessica",
    lastName: "Williams",
    email: "jessica.williams@example.com",
    phone: "567-890-1234",
    address: "202 Birch Street",
    city: "Someplace",
    state: "IL",
    country: "USA",
    zipCode: "77889",
  },
  {
    id: "6",
    firstName: "Daniel",
    lastName: "Jones",
    email: "daniel.jones@example.com",
    phone: "678-901-2345",
    address: "303 Cedar Street",
    city: "Anyplace",
    state: "PA",
    country: "USA",
    zipCode: "99000",
  },
  {
    id: "7",
    firstName: "Laura",
    lastName: "Garcia",
    email: "laura.garcia@example.com",
    phone: "789-012-3456",
    address: "404 Spruce Street",
    city: "Everyplace",
    state: "GA",
    country: "USA",
    zipCode: "22112",
  },
  {
    id: "8",
    firstName: "James",
    lastName: "Martinez",
    email: "james.martinez@example.com",
    phone: "890-123-4567",
    address: "505 Walnut Street",
    city: "Somewhere Else",
    state: "OH",
    country: "USA",
    zipCode: "33445",
  },
  {
    id: "9",
    firstName: "Sarah",
    lastName: "Rodriguez",
    email: "sarah.rodriguez@example.com",
    phone: "901-234-5678",
    address: "606 Chestnut Street",
    city: "Anywhere Else",
    state: "MI",
    country: "USA",
    zipCode: "55667",
  },
  {
    id: "10",
    firstName: "David",
    lastName: "Lee",
    email: "david.lee@example.com",
    phone: "012-345-6789",
    address: "707 Willow Street",
    city: "Everywhere Else",
    state: "NC",
    country: "USA",
    zipCode: "77890",
  },
  {
    id: "11",
    firstName: "Emma",
    lastName: "Perez",
    email: "emma.perez@example.com",
    phone: "123-456-7890",
    address: "808 Poplar Street",
    city: "Nowhere Else",
    state: "VA",
    country: "USA",
    zipCode: "88901",
  },
  {
    id: "12",
    firstName: "Alexander",
    lastName: "Thompson",
    email: "alexander.thompson@example.com",
    phone: "234-567-8901",
    address: "909 Fir Street",
    city: "Some City",
    state: "MA",
    country: "USA",
    zipCode: "99012",
  },
  {
    id: "13",
    firstName: "Olivia",
    lastName: "White",
    email: "olivia.white@example.com",
    phone: "345-678-9012",
    address: "1010 Pine Street",
    city: "Any City",
    state: "WA",
    country: "USA",
    zipCode: "11234",
  },
  {
    id: "14",
    firstName: "Liam",
    lastName: "Harris",
    email: "liam.harris@example.com",
    phone: "456-789-0123",
    address: "1111 Cedar Street",
    city: "Every City",
    state: "NJ",
    country: "USA",
    zipCode: "22345",
  },
  {
    id: "15",
    firstName: "Sophia",
    lastName: "Clark",
    email: "sophia.clark@example.com",
    phone: "567-890-1234",
    address: "1212 Spruce Street",
    city: "Somewhereville",
    state: "CO",
    country: "USA",
    zipCode: "33456",
  },
  {
    id: "16",
    firstName: "Mason",
    lastName: "Lewis",
    email: "mason.lewis@example.com",
    phone: "678-901-2345",
    address: "1313 Maple Street",
    city: "Anyplaceville",
    state: "OR",
    country: "USA",
    zipCode: "44567",
  },
  {
    id: "17",
    firstName: "Ava",
    lastName: "Walker",
    email: "ava.walker@example.com",
    phone: "789-012-3456",
    address: "1414 Oak Street",
    city: "Everyplaceville",
    state: "NV",
    country: "USA",
    zipCode: "55678",
  },
  {
    id: "18",
    firstName: "Ethan",
    lastName: "Young",
    email: "ethan.young@example.com",
    phone: "890-123-4567",
    address: "1515 Birch Street",
    city: "Someplaceville",
    state: "UT",
    country: "USA",
    zipCode: "66789",
  },
  {
    id: "19",
    firstName: "Isabella",
    lastName: "Hall",
    email: "isabella.hall@example.com",
    phone: "901-234-5678",
    address: "1616 Elm Street",
    city: "Anyplace Town",
    state: "AZ",
    country: "USA",
    zipCode: "77890",
  },
  {
    id: "20",
    firstName: "Logan",
    lastName: "Allen",
    email: "logan.allen@example.com",
    phone: "012-345-6789",
    address: "1717 Walnut Street",
    city: "Everyplace Town",
    state: "NM",
    country: "USA",
    zipCode: "88901",
  },
  {
    id: "21",
    firstName: "Mia",
    lastName: "Scott",
    email: "mia.scott@example.com",
    phone: "123-456-7890",
    address: "1818 Chestnut Street",
    city: "Nowhereville",
    state: "ID",
    country: "USA",
    zipCode: "99012",
  },
  {
    id: "22",
    firstName: "Lucas",
    lastName: "Green",
    email: "lucas.green@example.com",
    phone: "234-567-8901",
    address: "1919 Poplar Street",
    city: "Some City",
    state: "MT",
    country: "USA",
    zipCode: "11234",
  },
  {
    id: "23",
    firstName: "Amelia",
    lastName: "Baker",
    email: "amelia.baker@example.com",
    phone: "345-678-9012",
    address: "2020 Willow Street",
    city: "Any City",
    state: "SD",
    country: "USA",
    zipCode: "22345",
  },
  {
    id: "24",
    firstName: "Oliver",
    lastName: "Adams",
    email: "oliver.adams@example.com",
    phone: "456-789-0123",
    address: "2121 Fir Street",
    city: "Every City",
    state: "WY",
    country: "USA",
    zipCode: "33456",
  },
  {
    id: "25",
    firstName: "Charlotte",
    lastName: "Nelson",
    email: "charlotte.nelson@ex.com",
    phone: "567-890-1234",
    address: "2222 Pine Street",
    city: "Somewhereville",
    state: "DE",
    country: "USA",
    zipCode: "44567",
  },
];
