name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Release Please - Release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: react-pro-table
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Version
        id: extract_version
        run: echo "RELEASE_TAG=$(jq -r .tag_name <<< $(cat release-please-manifest.json))" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: Release ${{ env.RELEASE_TAG }}
          body: |
            Release notes for version ${{ env.RELEASE_TAG }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
